### ISSUE TITLE
Please tag releases in git

### ISSUE THREAD

**Issue by jonassmedegaard** [nrdvana/perl-Log-Any-Adapter-TAP#3]
Hi,

Current release on CPAN is 0.003003, but on Github is only tagged version 0.003.

Please tag releases, as that (if nothing else) helps distributors (like me: I currenlty look into packaging your nice library for Debian) wanting to track both formal releases and underlying git commits.

**Comment by nrdvana** [comment]
Sorry about that!  added the tag.  Also I've started using a Dist::Zilla plugin to keep it straight on my other projects, and will do that here too for the next release.

Quick question though, I was planning to change to a more brief version number for the next release, like "0.10".  Would that disturb anything you're working on, or do you need a fixed precision?

**Comment by jonassmedegaard** [comment]
Quoting M Conrad (2017-12-06 17:10:31)
> Sorry about that!  added the tag.  Also I've started using a 
> Dist::Zilla plugin to keep it straight on my other projects, and will 
> do that here too for the next release.

Excellent!


> Quick question though, I was planning to change to a more brief 
> version number for the next release, like "0.10".  Would that disturb 
> anything you're working on, or do you need a fixed precision?

I am (i.e. Debian is) flexible - thanks for your concer, but no need to 
worry about my/us :-)

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
